### ISSUE TITLE
Do not create GPU pod when running on main branch

### ISSUE THREAD

**Issue by rmarquis** [swiss-ai-center/a-guide-to-mlops#235]
Currently, the GPU pod is also created when pull request is merged into the main branch, before being destroyed without the intermediary step being executed. To restrict the GPU pod creation to only when a pull request is opened, two considerations must be addressed:

* The cleanup of the GPU pod should always be executed, even in the event of a failure, to prevent 'ghost' GPU pods from staying in the Kubernetes cluster.
* No code should be pushed to the main branch without prior training (`dvc repro` and `dvc push`). Branch protection rules need to be set up to enforce this requirement. This particular issue is tracked in #199.

**Comment by rmarquis** [comment]
It doesn't seem possible to run a step after the previous one has failed or has been cancelled, unless the condiftion `if: always()` is run.

tested:

```
cleanup-runner:
    needs: train-and-report
    runs-on: [self-hosted, base-runner]
    # Run this job if the event is a pull request or if the previous job was canceled or failed
    if: github.event_name == 'pull_request' || needs.train-and-report.result == 'failure' || needs.train-and-report.result == 'cancelled'
    steps:
      ...
```

Unfortunately, if we restrict the initial `setup-runner` to run on PR only (as it should be), this `if: always()` condition in `cleanup runner` will make it fails when merging the PR on the main branch (as it will always be executed, regardless of the previous steps being ran on PR only). This result in a "failure" cross on GitHub interface, which actually kinda defeat the warning purpose of the pipeline (but the pipeline works).
